# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  UserNameAndPasswordSecurityProvider:
    class: AppBundle\SecurityProviders\UserNameAndPasswordSecurityProvider
  TokenSecurityProvider:
    class: AppBundle\SecurityProviders\TokenSecurityProvider
  AdminLoginSecurityProvider:
    class: AppBundle\SecurityProviders\AdminLoginSecurityProvider
    arguments: ["%admin_username%","%admin_password%"]
  AdministratorProvider:
    class: AppBundle\SecurityProviders\AdminProvider
    arguments: ["%admin_username%","%admin_password%"]
  translation.loader.po:
    class: Symfony\Component\Translation\Loader\PoFileLoader
    tags:
      - { name: translation.loader, alias: po }
  translation.loader.mo:
    class: Symfony\Component\Translation\Loader\MoFileLoader
    tags:
      - { name: translation.loader, alias: mo }
  EmailSender:
    class: AppBundle\Utils\EmailSender
    arguments: ["@twig", "@mailer"]
  OfferMailerDomainService:
    class: AppBundle\DomainServices\OfferMailerDomainService
    arguments: ["@EmailSender", "%mailer_sender%", "%client_offer_endpoint%"]
  DealerConfirmationMail:
      class: AppBundle\Entity\DealerConfirmationMail
      arguments: ["@EmailSender", "%mailer_sender%", "%accepted_application_token_endpoint%"]
  DealerApplicationRegistry:
    class: AppBundle\Registry\DealerApplicationRegistry
    arguments: ["@doctrine"]
  DealerApplicationDomainService:
    class: AppBundle\DomainServices\DealerApplicationDomainService
    arguments: ["@DealerApplicationRegistry"]
  DealerApplicationService:
    class: AppBundle\ApplicationServices\DealerApplicationService
    arguments: ["@DealerApplicationDomainService", "@DealerConfirmationMail"]
  DealerConditionRegistry:
    class: AppBundle\Registry\DealerConditionsRegistry
    arguments: ["@doctrine"]
  DealerRegistry:
    class: AppBundle\Registry\DealerRegistry
    arguments: ["@doctrine"]
  ClientRegistry:
      class: AppBundle\Registry\ClientRegistry
      arguments: ["@doctrine"]
  GiftRegistry:
      class: AppBundle\Registry\GiftRegistry
      arguments: ["@doctrine"]
  ReviewRegistry:
      class: AppBundle\Registry\ReviewRegistry
      arguments: ["@doctrine"]
  ReviewDetailRegistry:
      class: AppBundle\Registry\ReviewDetailRegistry
      arguments: ["@doctrine"]
  OfferMessageRegistry:
      class: AppBundle\Registry\OfferMessageRegistry
      arguments: ["@doctrine"]
  DealerDomainService:
    class: AppBundle\DomainServices\DealerDomainService
    arguments: ["@DealerRegistry", "@DealerConditionRegistry", "@ReviewRegistry", "@ReviewDetailRegistry"]
  OfferMessageDomainService:
    class: AppBundle\DomainServices\OfferMessageDomainService
    arguments: ["@OfferMessageRegistry"]
  OfferMessageFileRegistry:
    class: AppBundle\Registry\OfferMessageFileRegistry
    arguments: ["@doctrine"]
  AttachmentDomainService:
    class: AppBundle\DomainServices\AttachmentDomainService
    arguments: ["@OfferMessageFileRegistry"]
  ClientDomainService:
      class: AppBundle\DomainServices\ClientDomainService
      arguments: ["@ClientRegistry"]
  GiftDomainService:
      class: AppBundle\DomainServices\GiftDomainService
      arguments: ["@GiftRegistry"]
  ReviewDomainService:
      class: AppBundle\DomainServices\ReviewDomainService
      arguments: ["@ReviewRegistry"]
  ReviewDetailDomainService:
      class: AppBundle\DomainServices\ReviewDetailDomainService
      arguments: ["@ReviewDetailRegistry"]
  OfferService:
    class: AppBundle\ApplicationServices\OfferService
    arguments: ["@ApplianceDomainService", "@OfferMessageDomainService", "@OfferMailerDomainService", "@DealerDomainService", "@AvatarDomainService", "@CarApplianceDomainService", "@DealerBackgroundImageDomainService", "@GoogleMapsAccessor"]
  DealerConditionDomainService:
    class: AppBundle\DomainServices\DealerConditionDomainService
    arguments: ["@DealerConditionRegistry"]
  AvatarRegistry:
    class: AppBundle\Registry\AvatarRegistry
    arguments: ["@doctrine"]
  AvatarDomainService:
    class: AppBundle\DomainServices\AvatarDomainService
    arguments: ["@AvatarRegistry"]
  AvailableCarsDomainService:
    class: AppBundle\DomainServices\AvailableCarsDomainService
    arguments: ["@AvailableCarsRegistry"]
  JatoRegistry:
    class: AppBundle\Registry\JatoRegistry
    arguments: ["@JatoAccessor"]
  VehicleRegistry:
      class: AppBundle\Registry\VehicleRegistry
      arguments: ["@JatoAccessor"]
  CarDomainService:
    class: AppBundle\DomainServices\CarDomainService
    arguments: ["@JatoRegistry"]
  VehicleDomainService:
      class: AppBundle\DomainServices\VehicleDomainService
      arguments: ["@VehicleRegistry"]
  CarService:
    class: AppBundle\ApplicationServices\CarService
    arguments: ["@CarDomainService", "@VehicleDomainService"]
  StockCarsRegistry:
    class: AppBundle\Registry\StockCarsRegistry
    arguments: ["@doctrine"]
  StockCarsDomainService:
    class: AppBundle\DomainServices\StockCarsDomainService
    arguments: ["@StockCarsRegistry"]
  GoogleMapsAccessor:
    class: AppBundle\Utils\GoogleMapsAccessor
  DealerService:
    class: AppBundle\ApplicationServices\DealerService
    arguments: ["@DealerDomainService", "@DealerApplicationDomainService", "@DealerConditionDomainService", "@AvatarDomainService", "@DealerBackgroundImageDomainService", "@AvailableCarsDomainService", "@CarDomainService", "@StockCarsDomainService", "@GoogleMapsAccessor"]
  CarApplianceRegistry:
    class: AppBundle\Registry\CarApplianceRegistry
    arguments: ["@doctrine"]
  CarApplianceFactory:
    class: AppBundle\Factory\CarApplianceFactory
  CarApplianceDomainService:
    class: AppBundle\DomainServices\CarApplianceDomainService
    arguments: ["@CarApplianceRegistry", "@JatoAccessor", "@CarApplianceFactory"]
  ApplianceOfferRegistry:
    class: AppBundle\Registry\ApplianceOfferRegistry
    arguments: ["@doctrine"]
  PacksDomainService:
    class: AppBundle\DomainServices\PacksDomainService
    arguments: ["@JatoRegistry"]
  PacksService:
    class: AppBundle\ApplicationServices\PacksService
    arguments: ["@PacksDomainService"]
  ApplianceDomainService:
    class: AppBundle\DomainServices\ApplianceOfferDomainService
    arguments: ["@ApplianceOfferRegistry", "@CarApplianceRegistry"]
  AppliancesForDealerDomainService:
    class: AppBundle\DomainServices\AppliancesForDealerDomainService
    arguments: ["@CarApplianceRegistry"]
  AppliancesForDealerService:
    class: AppBundle\ApplicationServices\AppliancesForDealerService
    arguments: ["@AppliancesForDealerDomainService", "@StockCarsDomainService", "@ApplianceDomainService"]
  AppliancesForClientService:
    class: AppBundle\ApplicationServices\AppliancesForClientService
    arguments: ["@AppliancesForClientDomainService"]
  AppliancesForClientDomainService:
    class: AppBundle\DomainServices\AppliancesForClientDomainService
    arguments: ["@CarApplianceRegistry"]
  ClientService:
      class: AppBundle\ApplicationServices\ClientService
      arguments: ["@ClientDomainService", "@GoogleMapsAccessor", "@CarApplianceDomainService", "@ApplianceDomainService", "@DealerDomainService", "@GiftDomainService", "%dealer_max_distance_km%"]
  DealerBackgroundImageRegistry:
    class: AppBundle\Registry\DealerBackgroundImageRegistry
    arguments: ["@doctrine"]
  CarApplianceService:
    class: AppBundle\ApplicationServices\CarApplianceService
    arguments: ["@CarApplianceDomainService", "@ClientDomainService", "@DealerDomainService", "@ApplianceDomainService", "@OfferMessageDomainService", "@AvatarDomainService", "@AttachmentDomainService", "%dealer_max_distance_km%"]
  DealerBackgroundImageDomainService:
    class: AppBundle\DomainServices\DealerBackgroundImageDomainService
    arguments: ["@DealerBackgroundImageRegistry"]
  CustomFileNamer:
    class: AppBundle\Utils\CustomFileNamer
  AttachmentNamer:
    class: AppBundle\Utils\AttachmentNamer
  Config:
    class: AppBundle\Config
  VehicleOptionsFilter:
    class: AppBundle\Utils\VehicleOptionsFilter
  JatoAccessor:
    class: AppBundle\Utils\JatoAccessor
    arguments: ["%jato_host%", "%jato_username%", "%jato_password%", "%jato_db%", "@Config", "@VehicleOptionsFilter"]
  AvailableCarsRegistry:
    class: AppBundle\Registry\AvailableCarsRegistry
    arguments: ["@doctrine"]
  LogoutService:
    class: AppBundle\ApplicationServices\LogoutService
  ReviewMailerDomainService:
    class: AppBundle\DomainServices\ReviewMailerDomainService
    arguments: ["@EmailSender", "%mailer_sender%"]
  ReviewService:
    class: AppBundle\ApplicationServices\ReviewService
    arguments: ["@ReviewDomainService", "@ReviewDetailDomainService", "@ClientDomainService", "@GiftDomainService", "@ReviewMailerDomainService"]